# Generated by Django 5.0.6 on 2024-06-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVERTER_IP_ADDRESS', models.GenericIPAddressField(default='192.168.88.176')),
                ('REFRESH_INTERVAL', models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(300)])),
                ('BATTERY_UPPER_LEVEL', models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(20)])),
                ('BATTERY_ENABLED', models.BooleanField(default=False)),
                ('CHARGE_THRESHOLD_EUR', models.FloatField(default=20, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
                ('CHARGE_HOURS', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('GRADIENT_THRESHOLD', models.FloatField(default=10.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('LOCAL_EXTREME_HOURS_WINDOW', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('BOJLER_ENABLED', models.BooleanField(default=True)),
                ('BOJLER_TAPO_IP_ADDRESS', models.GenericIPAddressField(default='192.168.88.180')),
                ('BOJLER_CONSUMPTION', models.IntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('CAR_ENABLED', models.BooleanField(default=True)),
                ('MAX_CURRENT_A', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)])),
                ('MIN_CURRENT_A', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)])),
            ],
        ),
    ]
