# Generated by Django 5.0.6 on 2024-09-05 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='BOJLER_TAPO_IP_ADDRESS',
            field=models.GenericIPAddressField(default='192.168.31.114'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='CHARGE_HOURS',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)]),
        ),
    ]
